function write_machine_details(machine_file::AbstractString)
    max_freq = read(`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`, String)
    FID = open(machine_file, "w")
    println(FID, "gethostname() = $(gethostname())")
    println(FID, "Sys.cpu_info()[1].model = $(Sys.cpu_info()[1].model)")
    println(FID, "julia VERSION = $(VERSION)")
    println(FID, "Sys.MACHINE = $(Sys.MACHINE)")
    println(FID, "Sys.CPU_NAME = $(Sys.CPU_NAME)")
    println(FID, "Sys.ARCH = $(Sys.ARCH)")
    println(FID, "Sys.KERNEL = $(Sys.KERNEL)")
    println(FID, "Sys.total_physical_memory() = $(Sys.total_physical_memory() / 1024^3) GB")
    println(FID, "max_freq = $(max_freq)")
    # println(FID, "run(`uname -a`) = $(run(`uname -a`))")
    # println(FID, "run(`lsb_release -a`) = $(run(`lsb_release -a`))")
    # println(FID, "run(`inxi -Sx`) = $(run(`inxi -Sx`))")
    # println(FID, "versioninfo(verbose=true) = $(versioninfo(verbose=true))")
    close(FID) 
end
